/* @macrome
 * @generatedby @bablr/macrome-generator-bablr
 * @generatedfrom ./grammar.macro.js#acaae6aa59de8ad314870c5af7f9fe7f5f06825d
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import _applyDecs from "@babel/runtime/helpers/applyDecs2305";
var _importMixin;
let _initProto;
import { re, spam as m } from '@bablr/boot';
import { AllowEmpty, CoveredBy, Node } from '@bablr/helpers/decorators';
import { eat, eatMatch, o } from '@bablr/helpers/grammar';
import { triviaEnhancer } from '@bablr/helpers/trivia';
import * as Comment from '@bablr/language-en-c-comments';
import * as es5 from '@bablr/language-en-es5';
import { mixin as classMixin } from './mixins/class.js';
import { mixin as importMixin } from './mixins/import.js';
export const dependencies = {
  Comment
};
export const canonicalURL = 'https://bablr.org/languages/universe/es6';
export const atrivialGrammar = class ES6Grammar extends (_importMixin = importMixin(classMixin(es5.atrivialGrammar))) {
  static {
    [_initProto] = _applyDecs(this, [[AllowEmpty, 2, "Statement"]], [], 0, void 0, _importMixin).e;
  }
  constructor(...args) {
    super(...args);
    _initProto(this);
  }
  *Statement(args) {
    if (yield eatMatch(m`<ImportDeclaration 'import' />`)) {} else if (yield eatMatch(m`<ExportDeclaration 'export' />`)) {} else {
      yield* super.Statement(args);
    }
  }
};
export const grammar = triviaEnhancer({
  triviaIsAllowed: s => s.span === 'Bare',
  triviaMatcher: m`#: :Comment: <_Trivia /[ \n\r\t]|\/\/|\/\*/ />`
}, atrivialGrammar);