/* @macrome
 * @generatedby @bablr/macrome-generator-bablr
 * @generatedfrom ./class.macro.js#7c7efbd53810742bbfe02e2071a3ba55e223ec2c
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import _applyDecs from "@babel/runtime/helpers/applyDecs2305";
import { spam as m } from '@bablr/boot';
import { CoveredBy, Node } from '@bablr/helpers/decorators';
import { eat, eatMatch } from '@bablr/helpers/grammar';
export const mixin = Base => {
  let _initProto, _ClassMethodDecs;
  return class ES6ClassGrammar extends Base {
    static {
      [_initProto] = _applyDecs(this, [[Node, 2, "ClassDeclaration"], [Node, 2, "ClassExpression"], [Node, 2, "ClassBody"], [_ClassMethodDecs, 2, "ClassMethod"], [Node, 2, "Super"]], [], 0, void 0, Base).e;
    }
    constructor(...args) {
      super(...args);
      _initProto(this);
    }
    *[(_ClassMethodDecs = [CoveredBy('ClassMember'), Node], "ClassDeclaration")]() {
      yield eat(m`class: <ClassExpression />`);
    }
    *ClassExpression() {
      yield eat(m`sigilToken: <*Keyword 'class' />`);
      yield eatMatch(m`name$: <Identifier />`);
      if (yield eatMatch(m`extendsToken: <*Keyword 'extends' />`)) {
        yield eat(m`superClass$: <__Expression>`);
      } else {
        yield eat(m`superClass$: null`);
      }
      yield eat(m`body: <ClassBody />`);
    }
    *ClassBody() {
      yield eat(m`openToken: <*Punctuator '{' { balanced: '}' } />`);
      while (yield eatMatch(m`members[]: <__ClassMember />`)) {}
      yield eat(m`closeToken: <*Punctuator '}' { balancer: true } />`);
    }
    *ClassMember() {
      yield eat(m`<ClassMethod>`);
    }
    *ClassMethod() {
      yield eatMatch(m`staticToken: <*Keyword 'static' />`);
      yield eatMatch(m`kindToken: <*Keyword /get|set/ />`);
      yield eat(m`value: <FunctionExpression />`);
    }
    *Super() {
      yield eat(m`sigilToken: <*Keyword 'super' />`);
    }
  };
};